#############################################################################
# Makefile for building: sortimg
# Generated by qmake (2.01a) (Qt 4.8.6) on: po b?e 9 19:18:24 2015
# Project:  sortimg.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile sortimg.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sortimg.cpp \
		pixmapviewer.cpp \
		qtopia_exif/qexifimageheader.cpp \
		fbiterator.cpp \
		filebank.cpp \
		imagebuffer.cpp \
		ibdata.cpp \
		scr.cpp moc_sortimg.cpp \
		moc_pixmapviewer.cpp \
		qrc_sortimg.cpp
OBJECTS       = sortimg.o \
		pixmapviewer.o \
		qexifimageheader.o \
		fbiterator.o \
		filebank.o \
		imagebuffer.o \
		ibdata.o \
		scr.o \
		moc_sortimg.o \
		moc_pixmapviewer.o \
		qrc_sortimg.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		sortimg.pro
QMAKE_TARGET  = sortimg
DESTDIR       = 
TARGET        = sortimg

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: sortimg.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile sortimg.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile sortimg.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/sortimg1.0.0 || $(MKDIR) .tmp/sortimg1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/sortimg1.0.0/ && $(COPY_FILE) --parents sortimg.h pixmapviewer.h qtopia_exif/qexifimageheader.h qtopia_exif/qtopiaglobal.h si_globals.h fbiterator.h filebank.h imagebuffer.h scr.h .tmp/sortimg1.0.0/ && $(COPY_FILE) --parents sortimg.qrc .tmp/sortimg1.0.0/ && $(COPY_FILE) --parents sortimg.cpp pixmapviewer.cpp qtopia_exif/qexifimageheader.cpp fbiterator.cpp filebank.cpp imagebuffer.cpp ibdata.cpp scr.cpp .tmp/sortimg1.0.0/ && (cd `dirname .tmp/sortimg1.0.0` && $(TAR) sortimg1.0.0.tar sortimg1.0.0 && $(COMPRESS) sortimg1.0.0.tar) && $(MOVE) `dirname .tmp/sortimg1.0.0`/sortimg1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/sortimg1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_sortimg.cpp moc_pixmapviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_sortimg.cpp moc_pixmapviewer.cpp
moc_sortimg.cpp: pixmapviewer.h \
		si_globals.h \
		scr.h \
		filebank.h \
		fbiterator.h \
		imagebuffer.h \
		qtopia_exif/qexifimageheader.h \
		qtopia_exif/qtopiaglobal.h \
		sortimg.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sortimg.h -o moc_sortimg.cpp

moc_pixmapviewer.cpp: si_globals.h \
		pixmapviewer.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) pixmapviewer.h -o moc_pixmapviewer.cpp

compiler_rcc_make_all: qrc_sortimg.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_sortimg.cpp
qrc_sortimg.cpp: sortimg.qrc \
		title.jpg
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name sortimg sortimg.qrc -o qrc_sortimg.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

sortimg.o: sortimg.cpp sortimg.h \
		pixmapviewer.h \
		si_globals.h \
		scr.h \
		filebank.h \
		fbiterator.h \
		imagebuffer.h \
		qtopia_exif/qexifimageheader.h \
		qtopia_exif/qtopiaglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sortimg.o sortimg.cpp

pixmapviewer.o: pixmapviewer.cpp pixmapviewer.h \
		si_globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pixmapviewer.o pixmapviewer.cpp

qexifimageheader.o: qtopia_exif/qexifimageheader.cpp qtopia_exif/qexifimageheader.h \
		qtopia_exif/qtopiaglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qexifimageheader.o qtopia_exif/qexifimageheader.cpp

fbiterator.o: fbiterator.cpp fbiterator.h \
		scr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fbiterator.o fbiterator.cpp

filebank.o: filebank.cpp filebank.h \
		scr.h \
		si_globals.h \
		fbiterator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filebank.o filebank.cpp

imagebuffer.o: imagebuffer.cpp imagebuffer.h \
		scr.h \
		si_globals.h \
		filebank.h \
		fbiterator.h \
		qtopia_exif/qexifimageheader.h \
		qtopia_exif/qtopiaglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagebuffer.o imagebuffer.cpp

ibdata.o: ibdata.cpp imagebuffer.h \
		scr.h \
		si_globals.h \
		filebank.h \
		fbiterator.h \
		qtopia_exif/qexifimageheader.h \
		qtopia_exif/qtopiaglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ibdata.o ibdata.cpp

scr.o: scr.cpp scr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scr.o scr.cpp

moc_sortimg.o: moc_sortimg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sortimg.o moc_sortimg.cpp

moc_pixmapviewer.o: moc_pixmapviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pixmapviewer.o moc_pixmapviewer.cpp

qrc_sortimg.o: qrc_sortimg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_sortimg.o qrc_sortimg.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

